services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: es_web_service
    ports:
      - "5432:5432"
    volumes:
      - es-db:/var/lib/postgresql/data

  web-service:
    build:
      context: .
    environment:
      NODE_ENV: production
      PORT: 1337
      DB_URI: postgres://postgres:postgres@postgres:5432
      DB_NAME: es_web_service

    depends_on:
      - postgres
    ports:
      - "1337:1337"

volumes:
  es-db:
