services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - '5432:5432'
    volumes:
      - es-db:/var/lib/postgresql/data

  web-service:
    build:
      context: .
    depends_on:
      - postgres
    ports:
    - '1337:1337'

volumes:
  es-db:
