services:
  nginx:
    image: linuxserver/swag
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - URL=bhkw.informaticore.net
      - VALIDATION=http
      - EMAIL=janik.steegmueller@student.uni-tuebingen.de
      - STAGING=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default:/config/nginx/site-confs/default

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: es_web_service
    ports:
      - "5432:5432"
    volumes:
      - es-db:/var/lib/postgresql/data

  web-service:
    image: jsteegmueller/bachelorthesis-bhkw
    environment:
      NODE_ENV: production
      PORT: 1337
      DB_URI: postgres://postgres:postgres@postgres:5432
      DB_NAME: es_web_service
      JWT_SECRET: secure
      CONTROL_ALGO_PATH: main.py
      OPEN_WEATHER_API_KEY: dfc57d64f0ddb809798fd887679e92f8

    depends_on:
      - postgres
    ports:
      - "1337:1337"

volumes:
  es-db:
